[project]
name = "aws-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "sagemaker>=2.244.0",
    "scikit-learn>=1.6.1",
]
